apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juicer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: juicer
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/multi-juicer
    repoURL: 'https://github.com/notdodo/multi-juicer'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
